version: 2
jobs:
  build:
    docker:
      - image: alpine:latest

    steps:
      - checkout
      - run:
          name: Testsuite
          command: >
            apk add --quiet --no-cache build-base openssl openssl-dev radare2-dev radare2 zlib-dev libzip-dev capstone-dev ;
            make run_tests ;
            mkdir -pv $(r2 -H R2_USER_PLUGINS) || sleep 0 ;
            make all install
